development:
  adapter: postgresql
  encoding: unicode
  database: greggit-dev
  pool: 5
  username: greg
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: greggit-test
  port: 5432
  pool: 5
  username: greg
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: greggit-prod
  pool: 5
  username: greg
  password: